name: Notify Testing Repository

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Send an HTTP trigger to the Testing repository
      - name: Trigger Testing Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"event_type": "triggered_by_developing"}' \
          https://api.github.com/repos/sneha6396/Testing/dispatches
